name: Big Data Modeling CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup Python Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python Code
        run: |
          pip install flake8
          flake8 scripts/

      - name: Run ETL Script
        run: |
          python scripts/etl.py

      - name: Run Spark Modeling Script
        run: |
          python scripts/spark_modeling.py

  database_check:
    name: Validate Database Scripts
    needs: test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bigdata_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install psycopg2-binary

      - name: Wait for Database to Start
        run: sleep 15

      - name: Setup Database Schema
        run: |
          psql -h localhost -U user -d bigdata_db -f sql/ddl.sql
        env:
          PGPASSWORD: password

      - name: Validate Database Loader
        run: |
          python scripts/database_loader.py
        env:
          PGPASSWORD: password

      - name: Run SQL Queries
        run: |
          psql -h localhost -U user -d bigdata_db -f sql/queries.sql
        env:
          PGPASSWORD: password
